// Score display: stored 0–100, shown Beli-style as 0–10 with one decimal
// ("8.7"). One place so every screen and share card agrees.
export function displayScore(score: number): string {
  return (score / 10).toFixed(1)
}

// The 0–100 score for a 0-based position in a list of `total` — a client mirror
// of the server's scoreFor (apps/api/src/lib/score.ts), used to preview a score
// before it's saved. Keep the two in sync.
export function scoreForPosition(index: number, total: number): number {
  if (total <= 1) return 95
  const top = 96
  const bottom = 72
  return Math.round(top - (index * (top - bottom)) / (total - 1))
}

// Price tier (1–4) as $ signs.
export function priceLabel(tier: number | null | undefined): string | null {
  if (!tier || tier < 1) return null
  return '$'.repeat(Math.min(tier, 4))
}

// Cuisine values are stored in English in the DB (seed + any future ingestion
// path) — translate at the display boundary so a data refresh never requires
// an app change, and existing/prod rows don't need a migration to read right.
// Unmapped values (a cuisine we haven't seen yet) pass through unchanged
// rather than disappearing.
//
// That passthrough is safe because the INGESTION side is closed, not because
// this map is exhaustive: both importers (googlePlaces.ts's
// GOOGLE_TYPE_TO_MESA_CUISINE and import-foursquare.ts's FSQ_TO_MESA_CUISINE)
// emit only keys that exist below and map anything unrecognized to null. So the
// only values that can reach here unmapped are the seed's own loanwords
// (Brasserie / Brunch / Tapas), which already read as Spanish. Keep that
// invariant: if you add an importer value, add its key here in the same commit.
const CUISINE_ES: Record<string, string> = {
  Contemporary: 'Contemporánea',
  Italian: 'Italiana',
  Spanish: 'Española',
  Basque: 'Vasca',
  Peruvian: 'Peruana',
  'Wine Bar': 'Bar de vinos',
  Dominican: 'Dominicana',
  Steakhouse: 'Parrilla',
  Mediterranean: 'Mediterránea',
  European: 'Europea',
  Mexican: 'Mexicana',
  Grill: 'A la parrilla',
  Japanese: 'Japonesa',
  Sandwiches: 'Sándwiches',
  Fusion: 'Fusión',
  // Added for the Foursquare import (M6) — cuisines the seed vocabulary didn't
  // cover but the real catalog does.
  Pizza: 'Pizza',
  Chinese: 'China',
  Thai: 'Tailandesa',
  Seafood: 'Mariscos',
  Café: 'Café',
}
export function cuisineLabel(cuisine: string | null | undefined): string | null {
  if (!cuisine) return null
  return CUISINE_ES[cuisine] ?? cuisine
}

// Occasion tags: the rank flow's own picker (RANK_TAGS in RankAPlace.tsx) is
// Spanish, but rows generated by the seed script predate that and are stored
// English — translate here so a restaurant's aggregated tag line never mixes
// languages regardless of which path wrote the row.
const TAG_ES: Record<string, string> = {
  'Date Night': 'Cena romántica',
  'Special Occasion': 'Ocasión especial',
  'Group Dinner': 'Cena en grupo',
  Outdoor: 'Al aire libre',
  'Fine Dining': 'Alta cocina',
  Casual: 'Informal',
  'Late Night': 'Trasnoche',
}
export function tagLabel(tag: string): string {
  return TAG_ES[tag] ?? tag
}

// Dish-photo grain treatment — shown as a mono "film · <grain>" tag and as a
// picker chip label (DishCompose).
export const GRAIN_LABEL_ES: Record<string, string> = {
  candlelit: 'Con velas',
  daylight: 'Luz de día',
  none: 'Ninguno',
}
export function grainLabel(grain: string | null | undefined): string {
  if (!grain) return GRAIN_LABEL_ES.candlelit as string
  return GRAIN_LABEL_ES[grain] ?? grain
}
