// @handles nobody may take: they would read as Mesa itself, its staff, or a page of the product. The
// check is on NEW handles only (a handle already held is never taken away), so an existing member whose
// handle is on this list can still save their profile.
const RESERVED = new Set([
  'mesa',
  'mesaapp',
  'mesa_app',
  'mesa.app',
  'mesasocial',
  'admin',
  'administrator',
  'administrador',
  'staff',
  'team',
  'equipo',
  'support',
  'soporte',
  'help',
  'ayuda',
  'moderator',
  'moderador',
  'mod',
  'mods',
  'official',
  'oficial',
  'security',
  'seguridad',
  'legal',
  'privacy',
  'privacidad',
  'terms',
  'terminos',
  'abuse',
  'contact',
  'contacto',
  'info',
  'hello',
  'hola',
  'root',
  'system',
  'sistema',
  'api',
  'www',
  'null',
  'undefined',
  'me',
  'you',
  'anonymous',
  'anonimo',
  'deleted',
  'eliminado',
])

export function isReservedHandle(handle: string): boolean {
  return RESERVED.has(handle.trim().toLowerCase().replace(/^@/, ''))
}
