// Menu section labels, by language — the raw `menu_items.section` string a
// restaurant's own menu uses as the map key (case-sensitive, matched exactly:
// see docs/MENUS.md for why section names are free text). Item names/
// descriptions stay untranslated by design (docs/MENUS.md), but a section
// header ("Entradas"/"Starters") is generic-enough category vocabulary that
// the language toggle should reach it.
//
// This is a BEST-EFFORT map, not exhaustive — a section name not listed here
// (a restaurant's own stylized title like "Zona de los Jefes" or "1505
// Heritage Dinner - Main") falls back to its raw string in both languages,
// which is the right behavior for something that reads as branding rather
// than a food category. `import-top100.ts --dry-run` warns about any newly
// imported section name that isn't mapped, so the list can grow deliberately
// rather than silently going stale.
export const MENU_SECTION_LABELS: Record<string, { es: string; en: string }> = {
  Entradas: { es: 'Entradas', en: 'Starters' },
  'Entradas / Para compartir': { es: 'Entradas / Para compartir', en: 'Starters / To share' },
  'Entradas Calientes': { es: 'Entradas Calientes', en: 'Hot Starters' },
  'Entradas Frías': { es: 'Entradas Frías', en: 'Cold Starters' },
  'Entradas - Calientes': { es: 'Entradas - Calientes', en: 'Starters - Hot' },
  'Entradas - Frías': { es: 'Entradas - Frías', en: 'Starters - Cold' },
  'Entradas - Caldos y sopas': { es: 'Entradas - Caldos y sopas', en: 'Starters - Broths & soups' },
  'Entradas - Croquetas sin gluten': {
    es: 'Entradas - Croquetas sin gluten',
    en: 'Starters - Gluten-free croquettes',
  },
  'Entradas de la Tierra': { es: 'Entradas de la Tierra', en: 'Land Starters' },
  'Entradas de la tierra': { es: 'Entradas de la tierra', en: 'Land starters' },
  'Entradas del Mar': { es: 'Entradas del Mar', en: 'Sea Starters' },
  'Entradas del mar': { es: 'Entradas del mar', en: 'Sea starters' },
  'Entradas crudas, frías & que queman': {
    es: 'Entradas crudas, frías & que queman',
    en: 'Raw, cold & spicy starters',
  },
  'Entrantes Calientes': { es: 'Entrantes Calientes', en: 'Hot Starters' },
  'Entrantes Fríos': { es: 'Entrantes Fríos', en: 'Cold Starters' },
  'Los Entrantes': { es: 'Los Entrantes', en: 'The Starters' },
  Entrees: { es: 'Entrantes', en: 'Entrees' },
  Entrées: { es: 'Entrantes', en: 'Entrees' },
  Entrepanes: { es: 'Entrepanes', en: 'Sandwiches' },
  Starters: { es: 'Entradas', en: 'Starters' },
  'Starter & To Share': { es: 'Para empezar / Compartir', en: 'Starter & To Share' },
  'Starters & Shareables': { es: 'Entradas para compartir', en: 'Starters & Shareables' },
  'Bites & Starters': { es: 'Bocados y entradas', en: 'Bites & Starters' },
  Appetizer: { es: 'Entrada', en: 'Appetizer' },
  Appetizers: { es: 'Entradas', en: 'Appetizers' },
  'Cold Appetizers': { es: 'Entradas Frías', en: 'Cold Appetizers' },
  'Hot Appetizers': { es: 'Entradas Calientes', en: 'Hot Appetizers' },
  'To Begin With': { es: 'Para empezar', en: 'To Begin With' },
  'Para empezar': { es: 'Para empezar', en: 'To Start' },
  "Pa' abrir el hambre": { es: "Pa' abrir el hambre", en: 'To Open Up Your Appetite' },
  'Para compartir': { es: 'Para compartir', en: 'To Share' },
  'Para Compartir': { es: 'Para Compartir', en: 'To Share' },
  'Plato para compartir': { es: 'Plato para compartir', en: 'Dish to Share' },
  'Pizzetas para compartir': { es: 'Pizzetas para compartir', en: 'Mini Pizzas to Share' },
  'Di condividere': { es: 'Para compartir', en: 'To Share' },
  'To Share': { es: 'Para compartir', en: 'To Share' },
  Aperitivos: { es: 'Aperitivos', en: 'Appetizers' },
  Antojos: { es: 'Antojos', en: 'Cravings' },
  Especialidad: { es: 'Especialidad', en: 'Specialty' },
  Especialidades: { es: 'Especialidades', en: 'Specialties' },
  Especiales: { es: 'Especiales', en: 'Specials' },
  'Selección Especial': { es: 'Selección Especial', en: 'Special Selection' },
  "Chef's Specialties": { es: 'Especialidades del Chef', en: "Chef's Specialties" },
  'Recomendación del Chef': { es: 'Recomendación del Chef', en: "Chef's Recommendation" },
  Recomendados: { es: 'Recomendados', en: 'Recommended' },
  'Más Populares': { es: 'Más Populares', en: 'Most Popular' },
  Highlights: { es: 'Destacados', en: 'Highlights' },
  'Highlights de carta': { es: 'Destacados de la carta', en: 'Menu Highlights' },
  'Menu Highlights': { es: 'Destacados del Menú', en: 'Menu Highlights' },
  'Official Menu Highlights': {
    es: 'Destacados Oficiales del Menú',
    en: 'Official Menu Highlights',
  },
  Featured: { es: 'Destacados', en: 'Featured' },
  'Artículos destacados': { es: 'Artículos destacados', en: 'Featured Items' },
  'Platos destacados / reseñas': {
    es: 'Platos destacados / reseñas',
    en: 'Featured Dishes / Reviews',
  },
  'Platos mencionados / reseñas': {
    es: 'Platos mencionados / reseñas',
    en: 'Mentioned Dishes / Reviews',
  },
  'Menciones en reseñas': { es: 'Menciones en reseñas', en: 'Mentioned in Reviews' },
  'Postres / reseñas': { es: 'Postres / reseñas', en: 'Desserts / Reviews' },
  'Popular / Digital Menu': { es: 'Popular / Menú Digital', en: 'Popular / Digital Menu' },
  'Top Rated / Digital Menu': {
    es: 'Mejor Valorado / Menú Digital',
    en: 'Top Rated / Digital Menu',
  },
  'Menú oficial verificado': { es: 'Menú oficial verificado', en: 'Verified Official Menu' },
  Nuevo: { es: 'Nuevo', en: 'New' },
  Extras: { es: 'Extras', en: 'Extras' },
  Descuentos: { es: 'Descuentos', en: 'Discounts' },
  Combos: { es: 'Combos', en: 'Combos' },
  Pack: { es: 'Pack', en: 'Pack' },
  Menu: { es: 'Menú', en: 'Menu' },
  Menú: { es: 'Menú', en: 'Menu' },
  Experiencia: { es: 'Experiencia', en: 'Experience' },
  'Elige Tu Experiencia': { es: 'Elige Tu Experiencia', en: 'Choose Your Experience' },

  Carnes: { es: 'Carnes', en: 'Meats' },
  Carne: { es: 'Carne', en: 'Meat' },
  Res: { es: 'Res', en: 'Beef' },
  'Carnes Blancas': { es: 'Carnes Blancas', en: 'White Meats' },
  'Carnes & Aves': { es: 'Carnes & Aves', en: 'Meats & Poultry' },
  'Carnes, Pollo y Mariscos': { es: 'Carnes, Pollo y Mariscos', en: 'Meats, Chicken & Seafood' },
  'Selección Carnes': { es: 'Selección Carnes', en: 'Meat Selection' },
  'Cortes de carne al carbón': { es: 'Cortes de carne al carbón', en: 'Charcoal-Grilled Cuts' },
  'Cortes Especiales & Combo': { es: 'Cortes Especiales & Combo', en: 'Special Cuts & Combo' },
  "Chef's Cuts": { es: 'Cortes del Chef', en: "Chef's Cuts" },
  'Plato Fuerte - Carnes': { es: 'Plato Fuerte - Carnes', en: 'Main Course - Meats' },
  Ave: { es: 'Ave', en: 'Poultry' },
  Aves: { es: 'Aves', en: 'Poultry' },
  'Plato Fuerte - Pollo': { es: 'Plato Fuerte - Pollo', en: 'Main Course - Chicken' },
  'Josper Grilled Meats': { es: 'Carnes a la Parrilla Josper', en: 'Josper Grilled Meats' },
  Asados: { es: 'Asados', en: 'Grilled' },
  'A la Parrilla': { es: 'A la Parrilla', en: 'Grilled' },
  'La parrilla': { es: 'La parrilla', en: 'The Grill' },
  Parrilladas: { es: 'Parrilladas', en: 'Grilled Platters' },
  'From The Farm To The Grill': {
    es: 'De la Granja a la Parrilla',
    en: 'From The Farm To The Grill',
  },
  'Steakhouse Corner': { es: 'Rincón Steakhouse', en: 'Steakhouse Corner' },
  'Legendary Steak Burgers': { es: 'Hamburguesas Legendarias', en: 'Legendary Steak Burgers' },

  Pescados: { es: 'Pescados', en: 'Fish' },
  'Los Pescados': { es: 'Los Pescados', en: 'The Fish' },
  'Selección Pescados': { es: 'Selección Pescados', en: 'Fish Selection' },
  'Pescados & Mariscos': { es: 'Pescados & Mariscos', en: 'Fish & Seafood' },
  'Pescados y Mariscos': { es: 'Pescados y Mariscos', en: 'Fish & Seafood' },
  'Frutos del Mar': { es: 'Frutos del Mar', en: 'Seafood' },
  'Frutti di mare': { es: 'Frutos del Mar', en: 'Seafood' },
  'Del Mar': { es: 'Del Mar', en: 'From the Sea' },
  'Del mar': { es: 'Del mar', en: 'From the sea' },
  'Rincón Marino': { es: 'Rincón Marino', en: 'Ocean Corner' },
  'Seafood & Fish': { es: 'Mariscos y Pescados', en: 'Seafood & Fish' },
  'Main Course / Sea': { es: 'Plato Principal / Mar', en: 'Main Course / Sea' },
  'Selección Langostas': { es: 'Selección Langostas', en: 'Lobster Selection' },
  Ostras: { es: 'Ostras', en: 'Oysters' },
  'Raw Bar': { es: 'Barra Fría', en: 'Raw Bar' },
  'Raw Mantico': { es: 'Barra Fría Mantico', en: 'Raw Bar Mantico' },
  Crudos: { es: 'Crudos', en: 'Raw' },
  'Barra Fría & Crudos': { es: 'Barra Fría & Crudos', en: 'Raw Bar & Crudos' },
  'Carpaccios y crudos': { es: 'Carpaccios y crudos', en: 'Carpaccios & Raw' },
  Carpaccios: { es: 'Carpaccios', en: 'Carpaccios' },
  Ceviche: { es: 'Ceviche', en: 'Ceviche' },
  Tiradito: { es: 'Tiradito', en: 'Tiradito' },
  Tiraditos: { es: 'Tiraditos', en: 'Tiraditos' },
  Tartar: { es: 'Tartar', en: 'Tartare' },
  Tartares: { es: 'Tartares', en: 'Tartares' },
  'Gambas / Camarones': { es: 'Gambas / Camarones', en: 'Shrimp' },

  Ensaladas: { es: 'Ensaladas', en: 'Salads' },
  'Ensaladas & Sopas': { es: 'Ensaladas & Sopas', en: 'Salads & Soups' },
  'Arma tu ensalada': { es: 'Arma tu ensalada', en: 'Build Your Own Salad' },
  Salads: { es: 'Ensaladas', en: 'Salads' },
  Salades: { es: 'Ensaladas', en: 'Salads' },
  Insalate: { es: 'Ensaladas', en: 'Salads' },
  'Salad Add-ons': { es: 'Extras para ensalada', en: 'Salad Add-ons' },
  'Bowls & Salads': { es: 'Bowls & Ensaladas', en: 'Bowls & Salads' },
  'Soups & Salads': { es: 'Sopas y Ensaladas', en: 'Soups & Salads' },
  'Smoothie Bowls': { es: 'Bowls de Batida', en: 'Smoothie Bowls' },
  'Sonoma Healthy Selection': { es: 'Selección Saludable Sonoma', en: 'Sonoma Healthy Selection' },

  Sopas: { es: 'Sopas', en: 'Soups' },
  'Sopas y Cremas': { es: 'Sopas y Cremas', en: 'Soups & Creams' },
  Caldos: { es: 'Caldos', en: 'Broths' },
  'Caldos de Aquí': { es: 'Caldos de Aquí', en: 'Local Broths' },
  Soups: { es: 'Sopas', en: 'Soups' },
  'Soups and Crepes': { es: 'Sopas y Crepas', en: 'Soups and Crepes' },
  'Tri Colored Soups': { es: 'Sopas Tricolor', en: 'Tri-Colored Soups' },
  Zuppe: { es: 'Sopas', en: 'Soups' },
  'De cuchara': { es: 'De cuchara', en: 'Spoon Dishes' },
  'Cuchara Brava': { es: 'Cuchara Brava', en: 'Bold Spoon Dishes' },

  Pastas: { es: 'Pastas', en: 'Pastas' },
  Pasta: { es: 'Pasta', en: 'Pasta' },
  'Pastas frescas': { es: 'Pastas frescas', en: 'Fresh Pastas' },
  'Pastas Caseras': { es: 'Pastas Caseras', en: 'Homemade Pastas' },
  'Pastas & Arroces': { es: 'Pastas & Arroces', en: 'Pastas & Rice' },
  'Pastas y Marisco': { es: 'Pastas y Marisco', en: 'Pastas & Seafood' },
  'Pastas y Pasta Fresca': { es: 'Pastas y Pasta Fresca', en: 'Pastas & Fresh Pasta' },
  'Pastas, Arroces y Crêpes': { es: 'Pastas, Arroces y Crêpes', en: 'Pastas, Rice & Crêpes' },
  'Pasta & Risotto': { es: 'Pasta & Risotto', en: 'Pasta & Risotto' },
  'Pasta y Risotto': { es: 'Pasta y Risotto', en: 'Pasta & Risotto' },
  'Pastas & Risottos': { es: 'Pastas & Risottos', en: 'Pastas & Risottos' },
  'Fresh Pasta & Risotto': { es: 'Pasta Fresca & Risotto', en: 'Fresh Pasta & Risotto' },
  'Handcrafted Pasta': { es: 'Pasta Artesanal', en: 'Handcrafted Pasta' },
  'Pasta speciale la forchetta': { es: 'Pasta especial del tenedor', en: 'Fork-Special Pasta' },
  Risotti: { es: 'Risottos', en: 'Risottos' },
  Risottos: { es: 'Risottos', en: 'Risottos' },
  'Paellas y Risottos': { es: 'Paellas y Risottos', en: 'Paellas & Risottos' },
  'Arroces, Risottos': { es: 'Arroces, Risottos', en: 'Rice & Risottos' },

  Arroces: { es: 'Arroces', en: 'Rice Dishes' },
  'Nuestros arroces': { es: 'Nuestros arroces', en: 'Our Rice Dishes' },
  'Arroces a la Brava': { es: 'Arroces a la Brava', en: 'Bold Rice Dishes' },
  'Arroces “machín-gon”': { es: 'Arroces "machín-gon"', en: '"Machín-gon" Rice' },
  'Arroces y Fideos': { es: 'Arroces y Fideos', en: 'Rice & Noodles' },
  'Arroces y Noodles': { es: 'Arroces y Noodles', en: 'Rice & Noodles' },
  'Wok, Rice & Noodles': { es: 'Wok, Arroz y Fideos', en: 'Wok, Rice & Noodles' },
  'Fried Rice': { es: 'Arroz Frito', en: 'Fried Rice' },

  Pizzas: { es: 'Pizzas', en: 'Pizzas' },
  Pizzeria: { es: 'Pizzería', en: 'Pizzeria' },
  'Pizzas Especiales': { es: 'Pizzas Especiales', en: 'Special Pizzas' },
  'Pizzas Tradicionales': { es: 'Pizzas Tradicionales', en: 'Traditional Pizzas' },
  'Arma tu Pizza': { es: 'Arma tu Pizza', en: 'Build Your Own Pizza' },
  'Pizza Bar': { es: 'Pizza Bar', en: 'Pizza Bar' },
  'Pizza & Focaccia': { es: 'Pizza & Focaccia', en: 'Pizza & Focaccia' },
  'Pizza / Focaccia': { es: 'Pizza / Focaccia', en: 'Pizza / Focaccia' },
  'Wood Oven Pizza & Focaccia': {
    es: 'Pizza y Focaccia al Horno de Leña',
    en: 'Wood Oven Pizza & Focaccia',
  },
  'Wood-Fired Pizza': { es: 'Pizza al Horno de Leña', en: 'Wood-Fired Pizza' },
  'Forno a Legna': { es: 'Horno de Leña', en: 'Wood-Fired Oven' },
  'Forno di Legna': { es: 'Horno de Leña', en: 'Wood-Fired Oven' },
  Calzone: { es: 'Calzone', en: 'Calzone' },

  Tacos: { es: 'Tacos', en: 'Tacos' },
  Burritos: { es: 'Burritos', en: 'Burritos' },
  'Bowls & Burritos': { es: 'Bowls & Burritos', en: 'Bowls & Burritos' },
  Quesadillas: { es: 'Quesadillas', en: 'Quesadillas' },
  'Saveurs du Mexique': { es: 'Sabores de México', en: 'Flavors of Mexico' },
  'Mexican - Entradas': { es: 'Mexicano - Entradas', en: 'Mexican - Starters' },

  Hamburguesas: { es: 'Hamburguesas', en: 'Burgers' },
  'Burgers & Sandwiches': { es: 'Hamburguesas & Sándwiches', en: 'Burgers & Sandwiches' },
  'Burgers - Smash': { es: 'Hamburguesas - Smash', en: 'Burgers - Smash' },
  'Burgers - Tradicionales': { es: 'Hamburguesas - Tradicionales', en: 'Burgers - Traditional' },
  'Smashed & Stacked': { es: 'Aplastadas y Apiladas', en: 'Smashed & Stacked' },
  Sándwiches: { es: 'Sándwiches', en: 'Sandwiches' },
  Sandwiches: { es: 'Sándwiches', en: 'Sandwiches' },
  'Sandwiches & Wraps': { es: 'Sándwiches & Wraps', en: 'Sandwiches & Wraps' },
  'Los Montaditos': { es: 'Los Montaditos', en: 'Mini Sandwiches' },
  Panuozzi: { es: 'Panuozzi', en: 'Panuozzi' },
  'Bar Snacks': { es: 'Piqueos de Bar', en: 'Bar Snacks' },
  Snacks: { es: 'Piqueos', en: 'Snacks' },

  Postres: { es: 'Postres', en: 'Desserts' },
  'The Sweets': { es: 'Postres', en: 'The Sweets' },
  'Postre, Café y Té': { es: 'Postre, Café y Té', en: 'Dessert, Coffee & Tea' },
  Dessert: { es: 'Postre', en: 'Dessert' },
  Sweet: { es: 'Dulce', en: 'Sweet' },
  Dolce: { es: 'Dulce', en: 'Sweet' },
  Dolci: { es: 'Postres', en: 'Desserts' },
  'Del Pastel': { es: 'Del Pastel', en: 'From the Cake' },
  'Bizcocho porción': { es: 'Bizcocho porción', en: 'Cake, by the slice' },
  'Bizcocho 1/4 libra': { es: 'Bizcocho 1/4 libra', en: 'Cake, quarter pound' },
  'Bizcocho 1/2 libra': { es: 'Bizcocho 1/2 libra', en: 'Cake, half pound' },
  'Final memorable': { es: 'Final memorable', en: 'A Memorable Finish' },

  Desayunos: { es: 'Desayunos', en: 'Breakfast' },
  Breakfast: { es: 'Desayuno', en: 'Breakfast' },
  'Kids Menu': { es: 'Menú de Niños', en: 'Kids Menu' },
  'Menú de Niños': { es: 'Menú de Niños', en: "Kids' Menu" },
  'Para los Más Pequeños': { es: 'Para los Más Pequeños', en: 'For the Little Ones' },
  'Para los marineritos': { es: 'Para los marineritos', en: 'For the Little Sailors' },

  Sushi: { es: 'Sushi', en: 'Sushi' },
  'Sushi Bar': { es: 'Sushi Bar', en: 'Sushi Bar' },
  'Sushi Bar / Nigiri Clásico (2 pzs)': {
    es: 'Sushi Bar / Nigiri Clásico (2 pzs)',
    en: 'Sushi Bar / Classic Nigiri (2 pcs)',
  },
  'Sushi Bar / Sashimi (4 pzs)': {
    es: 'Sushi Bar / Sashimi (4 pzs)',
    en: 'Sushi Bar / Sashimi (4 pcs)',
  },
  Makis: { es: 'Makis', en: 'Maki Rolls' },
  'Atarashii Makis': { es: 'Atarashii Makis', en: 'Atarashii Maki Rolls' },
  Rollos: { es: 'Rollos', en: 'Rolls' },
  Rolls: { es: 'Rollos', en: 'Rolls' },
  'Maki Rolls': { es: 'Rollos Maki', en: 'Maki Rolls' },
  'Featured / Maki': { es: 'Destacados / Maki', en: 'Featured / Maki' },
  'Rollo/Platos Sushi': { es: 'Rollo/Platos Sushi', en: 'Roll/Sushi Dishes' },
  Hosomakis: { es: 'Hosomakis', en: 'Hosomaki Rolls' },
  Sashimi: { es: 'Sashimi', en: 'Sashimi' },
  'Traditional Sashimi': { es: 'Sashimi Tradicional', en: 'Traditional Sashimi' },
  Niguiri: { es: 'Nigiri', en: 'Nigiri' },
  'Nigiri Traditional': { es: 'Nigiri Tradicional', en: 'Traditional Nigiri' },
  'Atarashii Nigiri': { es: 'Atarashii Nigiri', en: 'Atarashii Nigiri' },
  'Izakaya - Nigiris': { es: 'Izakaya - Nigiris', en: 'Izakaya - Nigiri' },
  'Atarashii Gunkan': { es: 'Atarashii Gunkan', en: 'Atarashii Gunkan' },
  'Gunkan Traditional': { es: 'Gunkan Tradicional', en: 'Traditional Gunkan' },
  Gyoza: { es: 'Gyoza', en: 'Gyoza' },
  'Dim Sum': { es: 'Dim Sum', en: 'Dim Sum' },
  'Selección Dim Sum': { es: 'Selección Dim Sum', en: 'Dim Sum Selection' },
  'Shiru Mono': { es: 'Shiru Mono', en: 'Shiru Mono' },
  Meinkozu: { es: 'Meinkozu', en: 'Meinkozu' },
  'Asian Corner': { es: 'Rincón Asiático', en: 'Asian Corner' },

  Antipasti: { es: 'Antipasti', en: 'Antipasti' },
  'Antipasti / agregador': { es: 'Antipasti', en: 'Antipasti' },
  Primi: { es: 'Primi', en: 'First Courses' },
  'Primi Piatti': { es: 'Primi Piatti', en: 'First Courses' },
  Secondi: { es: 'Secondi', en: 'Second Courses' },
  'Secondi Piatti': { es: 'Secondi Piatti', en: 'Second Courses' },
  'Piatti Signature': { es: 'Platos Signature', en: 'Signature Dishes' },
  'Di Stagione': { es: 'De Temporada', en: 'Seasonal' },
  Contorni: { es: 'Guarniciones', en: 'Side Dishes' },
  'Contornos / agregador': { es: 'Guarniciones', en: 'Side Dishes' },
  Salumeria: { es: 'Charcutería', en: 'Charcuterie' },
  Charcuterie: { es: 'Charcutería', en: 'Charcuterie' },
  'Mozzarella Bar': { es: 'Barra de Mozzarella', en: 'Mozzarella Bar' },
  'Alla Griglia': { es: 'A la Parrilla', en: 'Grilled' },

  Guarniciones: { es: 'Guarniciones', en: 'Side Dishes' },
  'Guarniciones especiales': { es: 'Guarniciones especiales', en: 'Special Side Dishes' },
  'Guarniciones Especiales': { es: 'Guarniciones Especiales', en: 'Special Side Dishes' },
  Guarnición: { es: 'Guarnición', en: 'Side Dish' },
  Acompañamientos: { es: 'Acompañamientos', en: 'Sides' },
  Acompañantes: { es: 'Acompañantes', en: 'Sides' },
  Sides: { es: 'Acompañamientos', en: 'Sides' },
  'To Complement': { es: 'Para Complementar', en: 'To Complement' },
  Verduras: { es: 'Verduras', en: 'Vegetables' },
  'Verduras & Hortalizas': { es: 'Verduras & Hortalizas', en: 'Vegetables & Greens' },
  'Verduras Frescas': { es: 'Verduras Frescas', en: 'Fresh Vegetables' },
  'Verduras y contornos': { es: 'Verduras y contornos', en: 'Vegetables & Sides' },
  Hortalizas: { es: 'Hortalizas', en: 'Greens' },
  'Del Jardín': { es: 'Del Jardín', en: 'From the Garden' },
  Vegan: { es: 'Vegano', en: 'Vegan' },
  Patatas: { es: 'Patatas', en: 'Potatoes' },
  Salsas: { es: 'Salsas', en: 'Sauces' },
  Guacamole: { es: 'Guacamole', en: 'Guacamole' },
  Importados: { es: 'Importados', en: 'Imported' },

  'Embutidos & Quesos': { es: 'Embutidos & Quesos', en: 'Cold Cuts & Cheeses' },
  'Los Embutidos': { es: 'Los Embutidos', en: 'The Cold Cuts' },
  'Las Croquetas': { es: 'Las Croquetas', en: 'The Croquettes' },
  Tablas: { es: 'Tablas', en: 'Sharing Boards' },
  Tapas: { es: 'Tapas', en: 'Tapas' },
  'Bar de Tapas': { es: 'Bar de Tapas', en: 'Tapas Bar' },
  'Tapas / agregador': { es: 'Tapas', en: 'Tapas' },
  'Para Tapeo': { es: 'Para Tapeo', en: 'For Tapas' },
  Crêpes: { es: 'Crêpes', en: 'Crêpes' },

  Platos: { es: 'Platos', en: 'Dishes' },
  'Platos / agregador': { es: 'Platos', en: 'Dishes' },
  'Platos Fuertes': { es: 'Platos Fuertes', en: 'Main Dishes' },
  'Platos Principales': { es: 'Platos Principales', en: 'Main Dishes' },
  Principales: { es: 'Principales', en: 'Mains' },
  Main: { es: 'Principal', en: 'Main' },
  Mains: { es: 'Principales', en: 'Mains' },
  Fuertes: { es: 'Fuertes', en: 'Mains' },
  'Mar & Tierra': { es: 'Mar & Tierra', en: 'Surf & Turf' },
  'Mar y Tierra': { es: 'Mar y Tierra', en: 'Surf & Turf' },
  'Signature Dishes': { es: 'Platos Signature', en: 'Signature Dishes' },
  'Chef Signature Fusion': { es: 'Fusión Signature del Chef', en: 'Chef Signature Fusion' },
  Grandes: { es: 'Grandes', en: 'Large Plates' },
  Medianos: { es: 'Medianos', en: 'Medium Plates' },
  Intermedios: { es: 'Intermedios', en: 'Intermediate Plates' },
  'Los Imperdibles': { es: 'Los Imperdibles', en: "Can't-Miss Dishes" },
  Calientes: { es: 'Calientes', en: 'Hot Dishes' },
  'De mi tierra': { es: 'De mi tierra', en: 'From My Homeland' },
  Mofongo: { es: 'Mofongo', en: 'Mofongo' },
  Tropicriollos: { es: 'Tropicriollos', en: 'Tropical Creole' },
  Tropipastas: { es: 'Tropipastas', en: 'Tropical Pastas' },

  Bambini: { es: 'Niños', en: 'Kids' },
  'Barra Caliente': { es: 'Barra Caliente', en: 'Hot Bar' },
  'Carta de Vinos - Blancos': { es: 'Carta de Vinos - Blancos', en: 'Wine List - Whites' },
  'Carta de Vinos - Rosados': { es: 'Carta de Vinos - Rosados', en: 'Wine List - Rosés' },
  'Carta de Vinos - Espumantes': { es: 'Carta de Vinos - Espumantes', en: 'Wine List - Sparkling' },
  'Carta de Vinos - Tintos': { es: 'Carta de Vinos - Tintos', en: 'Wine List - Reds' },
  'Mini tostaditas': { es: 'Mini tostaditas', en: 'Mini Toasts' },
  'Rincón Alternativo': { es: 'Rincón Alternativo', en: 'Alternative Corner' },
}

// Falls back to the raw section name in both languages when it isn't mapped
// above — the right behavior for a restaurant's own stylized section title
// ("Zona de los Jefes"), not just a gap to fill in later.
export function menuSectionLabel(name: string): { es: string; en: string } {
  return MENU_SECTION_LABELS[name] ?? { es: name, en: name }
}
