CREATE TABLE "dish_categories" (
	"id" text PRIMARY KEY NOT NULL,
	"group" text NOT NULL,
	"name_es" text NOT NULL,
	"sort_order" integer NOT NULL,
	"active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
ALTER TABLE "dishes" ALTER COLUMN "image_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "dishes" ADD COLUMN "category_id" text;--> statement-breakpoint
ALTER TABLE "dishes" ADD COLUMN "sentiment" text;--> statement-breakpoint
ALTER TABLE "dishes" ADD CONSTRAINT "dishes_category_id_dish_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."dish_categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
INSERT INTO "dish_categories" ("id", "group", "name_es", "sort_order", "active") VALUES
('mofongo', 'dominicano', 'Mofongo', 1, true),
('mangu', 'dominicano', 'Mangú y tres golpes', 2, true),
('guisado', 'dominicano', 'Guisados', 3, true),
('sancocho', 'dominicano', 'Sancocho y asopao', 4, true),
('criollo', 'dominicano', 'Plato criollo', 5, true),
('arroz', 'dominicano', 'Arroz y locrio', 6, true),
('fritura', 'dominicano', 'Frituras', 7, true),
('yaroa', 'dominicano', 'Yaroa y comida de calle', 8, true),
('dulce_criollo', 'dominicano', 'Dulces criollos', 9, true),
('tapas', 'espanol', 'Tapas', 10, true),
('paella', 'espanol', 'Paella y arroces', 11, true),
('embutidos', 'espanol', 'Jamón y embutidos', 12, true),
('arabe', 'mediterraneo', 'Árabe', 13, true),
('mezze', 'mediterraneo', 'Mezze y dips', 14, true),
('griego', 'mediterraneo', 'Griego', 15, true),
('pasta', 'italiano', 'Pasta', 16, true),
('pizza', 'italiano', 'Pizza', 17, true),
('risotto', 'italiano', 'Risotto', 18, true),
('antipasto', 'italiano', 'Antipasti', 19, true),
('frances', 'frances', 'Francés', 20, true),
('crepa', 'frances', 'Crepas y galettes', 21, true),
('hamburguesa', 'americano', 'Hamburguesas', 22, true),
('bbq', 'americano', 'BBQ y ahumados', 23, true),
('alitas', 'americano', 'Alitas', 24, true),
('americano', 'americano', 'Comfort americano', 25, true),
('sandwich', 'americano', 'Sándwiches y wraps', 26, true),
('tacos', 'latino', 'Tacos', 27, true),
('mexicano', 'latino', 'Mexicano', 28, true),
('arepa', 'latino', 'Arepas y venezolano', 29, true),
('peruano', 'latino', 'Peruano', 30, true),
('ceviche', 'latino', 'Ceviches y crudos', 31, true),
('parrilla', 'latino', 'Parrilla argentina', 32, true),
('latino', 'latino', 'Latino', 33, true),
('sushi', 'asiatico', 'Sushi y rolls', 34, true),
('poke', 'asiatico', 'Poke bowls', 35, true),
('ramen', 'asiatico', 'Ramen', 36, true),
('noodles', 'asiatico', 'Fideos asiáticos', 37, true),
('chino', 'asiatico', 'Comida china', 38, true),
('dim_sum', 'asiatico', 'Dim sum y dumplings', 39, true),
('japones', 'asiatico', 'Japonés', 40, true),
('coreano', 'asiatico', 'Coreano', 41, true),
('tailandes', 'asiatico', 'Tailandés', 42, true),
('indio', 'asiatico', 'Indio', 43, true),
('asiatico', 'asiatico', 'Asiático (otro)', 44, true),
('pescado', 'mar', 'Pescado', 45, true),
('mariscos', 'mar', 'Mariscos', 46, true),
('carne', 'carnes', 'Carnes y steaks', 47, true),
('cerdo', 'carnes', 'Cerdo', 48, true),
('pollo', 'carnes', 'Pollo', 49, true),
('entrada', 'entradas', 'Entradas y picaderas', 50, true),
('ensalada', 'entradas', 'Ensaladas', 51, true),
('sopa', 'entradas', 'Sopas y cremas', 52, true),
('saludable', 'entradas', 'Saludable y bowls', 53, true),
('brunch', 'desayuno', 'Desayuno y brunch', 54, true),
('panaderia', 'desayuno', 'Panadería y bollería', 55, true),
('postre', 'dulce', 'Postres', 56, true),
('torta', 'dulce', 'Tortas y pasteles', 57, true),
('helado', 'dulce', 'Helados y gelato', 58, true),
('cafe', 'bebidas', 'Café y té', 59, true),
('coctel', 'bebidas', 'Cócteles', 60, true),
('vino', 'bebidas', 'Vino', 61, true),
('cerveza', 'bebidas', 'Cerveza', 62, true),
('licor', 'bebidas', 'Ron y licores', 63, true),
('bebida', 'bebidas', 'Jugos y batidas', 64, true),
('otro', 'otro', 'Otro', 65, true)
ON CONFLICT ("id") DO NOTHING;
